apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-frontend
  template:
    metadata:
      labels:
        app: bike-frontend
    spec:
      containers:
      - name: frontend
        image: chittenaresh/bike-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend-service:3000"

